### PR TITLE
add pre-, post-, level-order traversals

### PR DESCRIPTION
**Pull request by spearman**
Adds iterators for pre-, post-, and level-order traversals.

### CODE REVIEW

**Comment by spearman** [comment]
There are a few places where .expect() is used to get a copy of a node ref, these could be eliminated if NodeRef could implement Clone.

**Comment by iwburns** [comment]
Thanks for yet another PR!

Sadly, it looks like this one also got tripped up by that conflict.

Otherwise though, this looks great as well.  I didn't go into super fine-grained detail on the implementations, but the doc-tests look right (and Travis says they passed) and no red flags are jumping out at me.

Once the conflict is resolved, I'll be good with merging this one.

**Comment by spearman** [comment]
Fixed

**Comment by iwburns** [comment]
Looks good, thanks for these!

**Comment by iwburns** [comment]
FYI, this and your other changes have been published under v0.1.4 on crates.io

**Pull request merged**
